include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "lib/firebase_options.dart"
    - "pubspec.yaml"

linter:
  rules:
    public_member_api_docs: false
