name: quizzylite
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-366.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper_view: ^1.1.8

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  go_router: ^6.5.1
  dartz: ^0.10.1
  path_provider: ^2.0.14
  flutter_riverpod: ^2.3.2
  shortid: ^0.1.2
  google_fonts: ^4.0.3
  translator: ^0.1.7
  percent_indicator: ^4.2.3
  collection: ^1.17.1
  firebase_crashlytics: ^3.3.4
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/sleeping_dog.png
    - assets/gifs/chill_relax.gif
    - assets/gifs/sleeping_with_pillow.gif
    - assets/gifs/thank_you.gif
    - assets/gifs/i_know_answer.gif
    - assets/gifs/thinkingDog.gif
    - assets/gifs/click.gif
