name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  flutter_test:
    name: Run Flutter analyze
    runs-on: ubuntu-latest
    steps:
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
