name: Flutter lint

on:
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.1"
      - name: Install FVM
        run: |
          dart pub global activate fvm
      - name: Install dependencies
        run: fvm flutter pub get
      - name: Analyze code
        run: fvm analyze
