name: Release Workflow
on:
  push:
    branches:
      - release
jobs:
  flutter_build_apk:
    name: Run Building Apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter build appbundle
  telegram_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build APK
        run: flutter build apk
      - name: Send APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TGCHANNELID }}
          token: ${{ secrets.TGBOTID }}
          message: New APK is available!
          document: ./build/app/outputs/apk/release/app-release.apk