name: Release Branch Workflow
on:
  push:
    branches:
      - release
jobs:
  flutter_test:
    name: Run Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - run: flutter pub run build_runner build
      - run: flutter analyze

   flutter_build_apk:
     name: Run Building Apk
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions/setup-java@v1
         with:
           java-version: "12.x"
           cache: 'gradle'
       - uses: subosito/flutter-action@v1
         with:
           channel: 'stable'
           cache: true
       - run: flutter pub get
       - run: flutter pub run build_runner build
       - run: flutter analyze
       - run: flutter build appbundle
